"""added rfid table

Revision ID: 170c932f771f
Revises: 1b44289b9409
Create Date: 2026-06-16 14:53:22.908729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '170c932f771f'
down_revision: Union[str, Sequence[str], None] = '1b44289b9409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bins', 'rfid_tag_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('bins', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('inventory', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('parts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('parts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('rfid_tags', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'bin_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'tx_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'tx_timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('transactions', 'bin_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'part_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rfid_tags', 'enrolled_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('parts', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('inventory', 'last_updated',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('bins', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('bins', 'rfid_tag_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # ### end Alembic commands ###
