"""added rfid table

Revision ID: 1b44289b9409
Revises: efd5cd02fbe7
Create Date: 2026-06-16 13:22:44.026728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b44289b9409'
down_revision: Union[str, Sequence[str], None] = 'efd5cd02fbe7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rfid_tags',
    sa.Column('rfid_uid', sa.String(length=100), nullable=False),
    sa.Column('part_id', sa.Integer(), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['part_id'], ['parts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rfid_uid')
    )
    op.create_index(op.f('ix_rfid_tags_rfid_uid'), 'rfid_tags', ['rfid_uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rfid_tags_rfid_uid'), table_name='rfid_tags')
    op.drop_table('rfid_tags')
    # ### end Alembic commands ###
